# Use the official PHP 7.4 
FROM php:7.4-fpm

# Install system dependencies
RUN apt-get update                                 
RUN docker-php-ext-install pdo pdo_mysql mysqli 
RUN docker-php-ext-enable pdo pdo_mysql mysqli 

# Copy the application files to the container
COPY ./source_files /var/www/html

# Set the working directory
WORKDIR /var/www/html

EXPOSE 9000